name: Documentation Quality Checks

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.py'
      - 'scripts/**'
      - 'app/**'
      - '.github/workflows/documentation-checks.yml'

jobs:
  validate-docstrings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest black sentence-transformers
          
      - name: Generate docstring validation report
        run: |
          python scripts/bidirectional_validate.py app/models/ml --output json > docstring_validation.json
          
      - name: Check docstring coverage threshold
        run: |
          python -c "
import json
with open('docstring_validation.json', 'r') as f:
    data = json.load(f)
threshold = 0.80
current = data['summary']['docstring_coverage']
print(f'Docstring coverage: {current:.2%} (minimum: {threshold:.2%})')
if current < threshold:
    print('::error::Docstring coverage is below threshold')
    exit(1)
          "
          
      - name: Check alignment score threshold
        run: |
          python -c "
import json
with open('docstring_validation.json', 'r') as f:
    data = json.load(f)
threshold = 0.70
current = data['summary']['alignment_score']
print(f'Code-doc alignment score: {current:.2%} (minimum: {threshold:.2%})')
if current < threshold:
    print('::error::Code-documentation alignment is below threshold')
    exit(1)
          "
          
      - name: Verify docstring examples
        run: |
          python scripts/verify_docstring_examples.py app/models/ml --recursive
          
      - name: Upload validation report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation-validation-report
          path: docstring_validation.json 